Drafty install script to dev on stretch

diff --git a/install_yunohost b/install_yunohost
--- a/install_yunohost
+++ b/install_yunohost
@@ -203,10 +203,44 @@ setup_package_source() {
 
     # Add YunoHost repository key to the keyring
     wget -O- https://repo.yunohost.org/yunohost.asc -q | apt-key add - -qq > /dev/null
+
+
+    ### FIXME / Rspamd upstream repo
+    #wget -O- https://rspamd.com/apt-stable/gpg.key | apt-key add -
+    #echo "deb http://rspamd.com/apt-stable/ stretch main" > /etc/apt/sources.list.d/rspamd.list
+}
+
+tmp_clone_packages() {
+
+    apt-get install dh-systemd python-all gdebi git
+    apt-get install git-buildpackage
+
+    # Dossier de dev
+    mkdir /ynh-dev/
+    cp ./Makefile /ynh-dev/Makefile
+    cp ./debconf /ynh-dev/debconf
+
+    # Metronome
+    cd /ynh-dev/
+    git clone https://github.com/yunohost/metronome
+    cd metronome
+    apt-get install lua5.1 liblua5.1-dev libidn11-dev libssl-dev txt2man quilt
+    dpkg-buildpackage -rfakeroot -uc -b -d
+    gdebi /ynh-dev/metronome_3.7.9+33b7572-1_amd64.deb
+
+    # Yunohost
+    cd /ynh-dev/
+    git clone https://github.com/yunohost/yunohost
+    cd yunohost
+    git checkout stretch
+
+    make repackage
+    make install
 }
 
 apt_update() {
-    apt_get_wrapper update
+    ### FIXME : allow-unauthenticated because weird bug with signatures...
+    apt_get_wrapper update --allow-unauthenticated
 }
 
 register_debconf() {
@@ -443,78 +477,37 @@ while getopts ":aid:h" option; do
   esac
 done
 
-if ! step ensure_root ; then
-  die "This script must be run as root" 1
-fi
+step ensure_root                   || die "This script must be run as root" 1
 
 if is_raspbian ; then
-    if ! step ensure_pi_logout ; then
-      die "The user pi should be logged out" 14
-    fi
+    step ensure_pi_logout          || die "The user pi should be logged out" 14
 fi
 
-if ! step upgrade_system ; then
-  die "Unable to update the system" 2
-fi
+step upgrade_system                || die "Unable to update the system" 2
+step installscript_dependencies    || die "Unable to install dependencies to install script" 3
+step create_custom_config          || die "Creating custom configuration file /etc/yunohost/yunohost.conf failed" 4
+step confirm_installation          || die "Installation cancelled at your request" 6
+step setup_package_source          || die "Setting up deb package sources failed" 7
+step apt_update                    || die "Error caught during 'apt-get update'" 8
 
-if ! step installscript_dependencies ; then
-  die "Unable to install dependencies to install script" 3
-fi
+# TMP / FIXME - tmp dev on stretch
+step tmp_clone_packages            || die "Derp" 666
 
-if ! step create_custom_config ; then
-  die "Creating custom configuration file /etc/yunohost/yunohost.conf failed" 4
-fi
+exit 0
 
-# if ! step set_domain ; then
-#   die "Setting hostname failed" 5
-# fi
-
-if ! step confirm_installation ; then
-  die "Installation cancelled at your request" 6
-fi
-
-if ! step setup_package_source ; then
-  die "Setting up deb package sources failed" 7
-fi
-
-if ! step apt_update ; then
-  die "Error caught during 'apt-get update'" 8
-fi
-
-if ! step register_debconf ; then
-  die "Unable to insert new values into debconf database" 9
-fi
-
-if ! step workaround_avahi_installation ; then
-  die "Unable to install workaround for avahi installation" 10
-fi
-
-if ! step install_yunohost_packages ; then
-  die "Installation of Yunohost packages failed" 11
-fi
-
-if ! step restart_services ; then
-  die "Error caught during services restart" 12
-fi
+step register_debconf              || die "Unable to insert new values into debconf database" 9
+step workaround_avahi_installation || die "Unable to install workaround for avahi installation" 10
+step install_yunohost_packages     || die "Installation of Yunohost packages failed" 11
+step restart_services              || die "Error caught during services restart" 12
 
 if is_raspbian ; then
-    if ! step del_user_pi ; then
-        die "Unable to delete user pi" 15
-    fi
-
-    if ! step change_hostname ; then
-        die "Unable to change hostname" 16
-    fi
-    
-    if ! step setup_firstboot ; then
-        die "Unable to setup firstboot" 17
-    fi
+    step del_user_pi     || die "Unable to delete user pi" 15
+    step change_hostname || die "Unable to change hostname" 16
+    step setup_firstboot || die "Unable to setup firstboot" 17
 fi
 
 if [[ "$BUILD_IMAGE" == "1" ]] ; then
-    if ! step clean_image ; then
-        die "Unable to clean image" 18
-    fi
+    step clean_image     || die "Unable to clean image" 18
 fi
 
 if is_raspbian ; then
@@ -522,9 +515,7 @@ if is_raspbian ; then
     reboot
 fi
 
-if ! step post_install ; then
-  die "Post-installation failed" 13 
-fi
+step post_install        || die "Post-installation failed" 13 
 
 
 # Success !
