Update install_yunohost

diff --git a/install_yunohost b/install_yunohost
--- a/install_yunohost
+++ b/install_yunohost
@@ -40,7 +40,7 @@ compactbutton=white,black
 function usage() {
   echo "
 Usage :
-  `basename $0` [-a] [-d <DISTRIB>] [-h]
+  $(basename "$0") [-a] [-d <DISTRIB>] [-h]
 
 Options :
   -a      Enable automatic mode. No questions are asked.
@@ -138,7 +138,7 @@ function build_packages_locally()
     apt install make -y
     mkdir -p /ynh-build/
     cp ./Makefile ./debconf /ynh-build/
-    cd /ynh-build
+    cd /ynh-build || exit
     make init
     make metronome
     make yunohost
@@ -146,7 +146,7 @@ function build_packages_locally()
 
 function install_local_packages()
 {
-    cd /ynh-build
+    cd /ynh-build || exit
     make install
 }
 
@@ -169,25 +169,25 @@ readonly white=$(printf '\033[39m')
 function success()
 {
   local msg=${1}
-  echo "[${bold}${green} OK ${normal}] ${msg}" | tee -a $YUNOHOST_LOG
+  echo "[${bold}${green} OK ${normal}] ${msg}" | tee -a "$YUNOHOST_LOG"
 }
 
 function info()
 {
   local msg=${1}
-  echo "[${bold}${blue}INFO${normal}] ${msg}" | tee -a $YUNOHOST_LOG
+  echo "[${bold}${blue}INFO${normal}] ${msg}" | tee -a "$YUNOHOST_LOG"
 }
 
 function warn()
 {
   local msg=${1}
-  echo "[${bold}${orange}WARN${normal}] ${msg}" | tee -a $YUNOHOST_LOG >&2
+  echo "[${bold}${orange}WARN${normal}] ${msg}" | tee -a "$YUNOHOST_LOG" >&2
 }
 
 function error()
 {
   local msg=${1}
-  echo "[${bold}${red}FAIL${normal}] ${msg}" | tee -a $YUNOHOST_LOG >&2
+  echo "[${bold}${red}FAIL${normal}] ${msg}" | tee -a "$YUNOHOST_LOG" >&2
 }
 
 function die() {
@@ -207,11 +207,11 @@ function apt_get_wrapper() {
     if [[ "$AUTOMODE" == "0" ]] ;
     then
       debconf-apt-progress                             \
-          --logfile $YUNOHOST_LOG                      \
+          --logfile "$YUNOHOST_LOG"                      \
           --                                           \
-          apt-get $*
+          apt-get "$*"
     else
-        apt-get $* 2>&1 | tee -a $YUNOHOST_LOG
+        apt-get "$*" 2>&1 | tee -a "$YUNOHOST_LOG"
     fi
 }
 
@@ -302,7 +302,7 @@ function upgrade_system() {
         || return 3
 
     	if [[ "$BUILD_IMAGE" != "1" ]] ; then
-		(rpi-update 2>&1 | tee -a $YUNOHOST_LOG) \
+		(rpi-update 2>&1 | tee -a "$YUNOHOST_LOG") \
 		|| return 4
 	fi
     fi
@@ -320,7 +320,7 @@ function install_script_dependencies() {
     apt_update
     apt_get_wrapper -o Dpkg::Options::="--force-confold" \
                     -y --force-yes install               \
-                    $DEPENDENCIES                        \
+                    "$DEPENDENCIES"                        \
       || return 1
 }
 
@@ -574,7 +574,7 @@ function user_pi_logged_out() {
 
 function del_user_pi() {
     if id "pi" >/dev/null 2>&1; then
-        deluser --remove-all-files pi >> $YUNOHOST_LOG 2>&1
+        deluser --remove-all-files pi >> "$YUNOHOST_LOG" 2>&1
     fi
 }
 
@@ -584,16 +584,16 @@ function del_user_pi() {
 
 function clean_image() {
     # Delete SSH keys
-    rm -f /etc/ssh/ssh_host_* >> $YUNOHOST_LOG 2>&1
-    yes | ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa >> $YUNOHOST_LOG 2>&1
-    yes | ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa >> $YUNOHOST_LOG 2>&1
-    yes | ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa -b 521 >> $YUNOHOST_LOG 2>&1
+    rm -f /etc/ssh/ssh_host_* >> "$YUNOHOST_LOG" 2>&1
+    yes | ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa >> "$YUNOHOST_LOG" 2>&1
+    yes | ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa >> "$YUNOHOST_LOG" 2>&1
+    yes | ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa -b 521 >> "$YUNOHOST_LOG" 2>&1
 
     # Deleting logs ...
-    find /var/log -type f -exec rm {} \; >> $YUNOHOST_LOG 2>&1
+    find /var/log -type f -exec rm {} \; >> "$YUNOHOST_LOG" 2>&1
 
     # Purging apt ...
-    apt-get clean >> $YUNOHOST_LOG 2>&1
+    apt-get clean >> "$YUNOHOST_LOG" 2>&1
 }
 
 
